## **Narendirakumar A**
## **Gangaraju Tharun**
## **Nithil Eshwar Mani**
## **Thumula Praneeth Rao**

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print('The diamater of {} is {} kilometers'.format(planet,diameter))

The diamater of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr2=np.ones(10)*5
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
arr3=np.arange(20,35,2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr4=np.arange(0,9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
arr5=np.concatenate((a,b),axis=0)
arr5

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [14]:
data=np.array([(1,2),(3,4),(5,6)])
pd1=pd.DataFrame(data,columns=['a','b'])
pd1

   a  b
0  1  2
1  3  4
2  5  6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import datetime
pd2=pd.date_range(start="2023-01-01",end="2023-02-10")
pd2

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
pd3=pd.DataFrame(lists,columns=['id','name','age'])
pd3

   id name  age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24